#ifndef __MESSAGE__
#define __MESSAGE__

#include <stdint.h>
#define BUFFER_SIZE 1024

enum MessageType
{
  SIGNUP_REQUEST = 0,
  LOGIN_REQUEST = 1,
  LOGOUT_REQUEST = 2,
  LIST_USER = 3,
  GAME_START = 5,
  GAME_GUESS = 6,
  GAME_TURN = 7,
  GAME_END = 8,
  GAME_GET_TARGET = 9,
  GAME_JOIN = 10,
  GAME_LEAVE = 11,
  GAME_UPDATE = 12,
  GAME_SCORE = 17,
  CHALLANGE_REQUEST = 13,
  CHALLANGE_RESPONSE = 14,
  CHALLANGE_CANCEL = 15,
  LIST_GAME_HISTORY = 16,
  GAME_DETAIL_REQUEST = 18,
  GET_SCORE_BY_USER_REQUEST = 19,
  GAME_TIMEOUT = 20,
};

enum StatusCode
{
  SUCCESS = 200,
  CREATED = 201,
  ACCEPTED = 202,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  SERVICE_UNAVAILABLE = 503
};

typedef struct
{
  enum MessageType message_type;
  enum StatusCode status;
  char payload[BUFFER_SIZE];
} Message;

#endif
